package first.netty_demo;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeaderProtocol.proto

public final class HeaderProtocol {
  private HeaderProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 version = 1;
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     * 协议版本号
     * </pre>
     */
    boolean hasVersion();
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     * 协议版本号
     * </pre>
     */
    int getVersion();

    // required int32 cseq = 2;
    /**
     * <code>required int32 cseq = 2;</code>
     *
     * <pre>
     * 消息序列号
     * </pre>
     */
    boolean hasCseq();
    /**
     * <code>required int32 cseq = 2;</code>
     *
     * <pre>
     * 消息序列号
     * </pre>
     */
    int getCseq();

    // optional .Header.MsgType msgType = 3;
    /**
     * <code>optional .Header.MsgType msgType = 3;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    boolean hasMsgType();
    /**
     * <code>optional .Header.MsgType msgType = 3;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    HeaderProtocol.Header.MsgType getMsgType();
    /**
     * <code>optional .Header.MsgType msgType = 3;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    HeaderProtocol.Header.MsgTypeOrBuilder getMsgTypeOrBuilder();
  }
  /**
   * Protobuf type {@code Header}
   *
   * <pre>
   *
   * @brief 头部(协议层数据)
   * </pre>
   */
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Header(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }

    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              version_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cseq_ = input.readInt32();
              break;
            }
            case 26: {
              HeaderProtocol.Header.MsgType.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = msgType_.toBuilder();
              }
              msgType_ = input.readMessage(HeaderProtocol.Header.MsgType.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(msgType_);
                msgType_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeaderProtocol.internal_static_Header_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeaderProtocol.internal_static_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeaderProtocol.Header.class, HeaderProtocol.Header.Builder.class);
    }

    public static com.google.protobuf.Parser<Header> PARSER =
        new com.google.protobuf.AbstractParser<Header>() {
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    public interface MsgTypeOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];
      /**
       * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
       *
       * <pre>
       * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
       * </pre>
       */
      boolean hasType();
      /**
       * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
       *
       * <pre>
       * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
       * </pre>
       */
      HeaderProtocol.Header.MsgType.MessageType getType();

      // optional string extends = 2;
      /**
       * <code>optional string extends = 2;</code>
       *
       * <pre>
       * 扩展信息   
       * </pre>
       */
      boolean hasExtends();
      /**
       * <code>optional string extends = 2;</code>
       *
       * <pre>
       * 扩展信息   
       * </pre>
       */
      java.lang.String getExtends();
      /**
       * <code>optional string extends = 2;</code>
       *
       * <pre>
       * 扩展信息   
       * </pre>
       */
      com.google.protobuf.ByteString
          getExtendsBytes();
    }
    /**
     * Protobuf type {@code Header.MsgType}
     */
    public static final class MsgType extends
        com.google.protobuf.GeneratedMessage
        implements MsgTypeOrBuilder {
      // Use MsgType.newBuilder() to construct.
      private MsgType(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MsgType(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MsgType defaultInstance;
      public static MsgType getDefaultInstance() {
        return defaultInstance;
      }

      public MsgType getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MsgType(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                HeaderProtocol.Header.MsgType.MessageType value = HeaderProtocol.Header.MsgType.MessageType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  type_ = value;
                }
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                extends_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeaderProtocol.internal_static_Header_MsgType_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeaderProtocol.internal_static_Header_MsgType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeaderProtocol.Header.MsgType.class, HeaderProtocol.Header.MsgType.Builder.class);
      }

      public static com.google.protobuf.Parser<MsgType> PARSER =
          new com.google.protobuf.AbstractParser<MsgType>() {
        public MsgType parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MsgType(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MsgType> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code Header.MsgType.MessageType}
       */
      public enum MessageType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>REQUEST = 0;</code>
         *
         * <pre>
         * 请求   
         * </pre>
         */
        REQUEST(0, 0),
        /**
         * <code>RESPONSE = 1;</code>
         *
         * <pre>
         * 响应   
         * </pre>
         */
        RESPONSE(1, 1),
        /**
         * <code>NOTIFY = 2;</code>
         *
         * <pre>
         * 通知   
         * </pre>
         */
        NOTIFY(2, 2),
        ;

        /**
         * <code>REQUEST = 0;</code>
         *
         * <pre>
         * 请求   
         * </pre>
         */
        public static final int REQUEST_VALUE = 0;
        /**
         * <code>RESPONSE = 1;</code>
         *
         * <pre>
         * 响应   
         * </pre>
         */
        public static final int RESPONSE_VALUE = 1;
        /**
         * <code>NOTIFY = 2;</code>
         *
         * <pre>
         * 通知   
         * </pre>
         */
        public static final int NOTIFY_VALUE = 2;


        public final int getNumber() { return value; }

        public static MessageType valueOf(int value) {
          switch (value) {
            case 0: return REQUEST;
            case 1: return RESPONSE;
            case 2: return NOTIFY;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<MessageType>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
                public MessageType findValueByNumber(int number) {
                  return MessageType.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return HeaderProtocol.Header.MsgType.getDescriptor().getEnumTypes().get(0);
        }

        private static final MessageType[] VALUES = values();

        public static MessageType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private MessageType(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:Header.MsgType.MessageType)
      }

      private int bitField0_;
      // optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];
      public static final int TYPE_FIELD_NUMBER = 1;
      private HeaderProtocol.Header.MsgType.MessageType type_;
      /**
       * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
       *
       * <pre>
       * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
       *
       * <pre>
       * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
       * </pre>
       */
      public HeaderProtocol.Header.MsgType.MessageType getType() {
        return type_;
      }

      // optional string extends = 2;
      public static final int EXTENDS_FIELD_NUMBER = 2;
      private java.lang.Object extends_;
      /**
       * <code>optional string extends = 2;</code>
       *
       * <pre>
       * 扩展信息   
       * </pre>
       */
      public boolean hasExtends() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string extends = 2;</code>
       *
       * <pre>
       * 扩展信息   
       * </pre>
       */
      public java.lang.String getExtends() {
        java.lang.Object ref = extends_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            extends_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string extends = 2;</code>
       *
       * <pre>
       * 扩展信息   
       * </pre>
       */
      public com.google.protobuf.ByteString
          getExtendsBytes() {
        java.lang.Object ref = extends_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          extends_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        type_ = HeaderProtocol.Header.MsgType.MessageType.NOTIFY;
        extends_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getExtendsBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, type_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getExtendsBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static HeaderProtocol.Header.MsgType parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderProtocol.Header.MsgType parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderProtocol.Header.MsgType parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static HeaderProtocol.Header.MsgType parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static HeaderProtocol.Header.MsgType parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static HeaderProtocol.Header.MsgType parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static HeaderProtocol.Header.MsgType parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static HeaderProtocol.Header.MsgType parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static HeaderProtocol.Header.MsgType parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static HeaderProtocol.Header.MsgType parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(HeaderProtocol.Header.MsgType prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Header.MsgType}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements HeaderProtocol.Header.MsgTypeOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return HeaderProtocol.internal_static_Header_MsgType_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return HeaderProtocol.internal_static_Header_MsgType_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  HeaderProtocol.Header.MsgType.class, HeaderProtocol.Header.MsgType.Builder.class);
        }

        // Construct using HeaderProtocol.Header.MsgType.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          type_ = HeaderProtocol.Header.MsgType.MessageType.NOTIFY;
          bitField0_ = (bitField0_ & ~0x00000001);
          extends_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return HeaderProtocol.internal_static_Header_MsgType_descriptor;
        }

        public HeaderProtocol.Header.MsgType getDefaultInstanceForType() {
          return HeaderProtocol.Header.MsgType.getDefaultInstance();
        }

        public HeaderProtocol.Header.MsgType build() {
          HeaderProtocol.Header.MsgType result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public HeaderProtocol.Header.MsgType buildPartial() {
          HeaderProtocol.Header.MsgType result = new HeaderProtocol.Header.MsgType(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.extends_ = extends_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof HeaderProtocol.Header.MsgType) {
            return mergeFrom((HeaderProtocol.Header.MsgType)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(HeaderProtocol.Header.MsgType other) {
          if (other == HeaderProtocol.Header.MsgType.getDefaultInstance()) return this;
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasExtends()) {
            bitField0_ |= 0x00000002;
            extends_ = other.extends_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          HeaderProtocol.Header.MsgType parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (HeaderProtocol.Header.MsgType) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];
        private HeaderProtocol.Header.MsgType.MessageType type_ = HeaderProtocol.Header.MsgType.MessageType.NOTIFY;
        /**
         * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
         *
         * <pre>
         * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
         * </pre>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
         *
         * <pre>
         * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
         * </pre>
         */
        public HeaderProtocol.Header.MsgType.MessageType getType() {
          return type_;
        }
        /**
         * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
         *
         * <pre>
         * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
         * </pre>
         */
        public Builder setType(HeaderProtocol.Header.MsgType.MessageType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .Header.MsgType.MessageType type = 1 [default = NOTIFY];</code>
         *
         * <pre>
         * 发送目标类型，包括服务、服务类型以及客户端，默认为服务，如果是服务类型，则主要用于通知 
         * </pre>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          type_ = HeaderProtocol.Header.MsgType.MessageType.NOTIFY;
          onChanged();
          return this;
        }

        // optional string extends = 2;
        private java.lang.Object extends_ = "";
        /**
         * <code>optional string extends = 2;</code>
         *
         * <pre>
         * 扩展信息   
         * </pre>
         */
        public boolean hasExtends() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string extends = 2;</code>
         *
         * <pre>
         * 扩展信息   
         * </pre>
         */
        public java.lang.String getExtends() {
          java.lang.Object ref = extends_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            extends_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string extends = 2;</code>
         *
         * <pre>
         * 扩展信息   
         * </pre>
         */
        public com.google.protobuf.ByteString
            getExtendsBytes() {
          java.lang.Object ref = extends_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            extends_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string extends = 2;</code>
         *
         * <pre>
         * 扩展信息   
         * </pre>
         */
        public Builder setExtends(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          extends_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string extends = 2;</code>
         *
         * <pre>
         * 扩展信息   
         * </pre>
         */
        public Builder clearExtends() {
          bitField0_ = (bitField0_ & ~0x00000002);
          extends_ = getDefaultInstance().getExtends();
          onChanged();
          return this;
        }
        /**
         * <code>optional string extends = 2;</code>
         *
         * <pre>
         * 扩展信息   
         * </pre>
         */
        public Builder setExtendsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          extends_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Header.MsgType)
      }

      static {
        defaultInstance = new MsgType(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Header.MsgType)
    }

    private int bitField0_;
    // required int32 version = 1;
    public static final int VERSION_FIELD_NUMBER = 1;
    private int version_;
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     * 协议版本号
     * </pre>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 version = 1;</code>
     *
     * <pre>
     * 协议版本号
     * </pre>
     */
    public int getVersion() {
      return version_;
    }

    // required int32 cseq = 2;
    public static final int CSEQ_FIELD_NUMBER = 2;
    private int cseq_;
    /**
     * <code>required int32 cseq = 2;</code>
     *
     * <pre>
     * 消息序列号
     * </pre>
     */
    public boolean hasCseq() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 cseq = 2;</code>
     *
     * <pre>
     * 消息序列号
     * </pre>
     */
    public int getCseq() {
      return cseq_;
    }

    // optional .Header.MsgType msgType = 3;
    public static final int MSGTYPE_FIELD_NUMBER = 3;
    private HeaderProtocol.Header.MsgType msgType_;
    /**
     * <code>optional .Header.MsgType msgType = 3;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .Header.MsgType msgType = 3;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    public HeaderProtocol.Header.MsgType getMsgType() {
      return msgType_;
    }
    /**
     * <code>optional .Header.MsgType msgType = 3;</code>
     *
     * <pre>
     * 消息类型
     * </pre>
     */
    public HeaderProtocol.Header.MsgTypeOrBuilder getMsgTypeOrBuilder() {
      return msgType_;
    }

    private void initFields() {
      version_ = 0;
      cseq_ = 0;
      msgType_ = HeaderProtocol.Header.MsgType.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCseq()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cseq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, msgType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, version_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cseq_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, msgType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static HeaderProtocol.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeaderProtocol.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeaderProtocol.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeaderProtocol.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeaderProtocol.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeaderProtocol.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HeaderProtocol.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HeaderProtocol.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HeaderProtocol.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeaderProtocol.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HeaderProtocol.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Header}
     *
     * <pre>
     *
     * @brief 头部(协议层数据)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements HeaderProtocol.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeaderProtocol.internal_static_Header_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeaderProtocol.internal_static_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeaderProtocol.Header.class, HeaderProtocol.Header.Builder.class);
      }

      // Construct using HeaderProtocol.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMsgTypeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cseq_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (msgTypeBuilder_ == null) {
          msgType_ = HeaderProtocol.Header.MsgType.getDefaultInstance();
        } else {
          msgTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeaderProtocol.internal_static_Header_descriptor;
      }

      public HeaderProtocol.Header getDefaultInstanceForType() {
        return HeaderProtocol.Header.getDefaultInstance();
      }

      public HeaderProtocol.Header build() {
        HeaderProtocol.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeaderProtocol.Header buildPartial() {
        HeaderProtocol.Header result = new HeaderProtocol.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cseq_ = cseq_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (msgTypeBuilder_ == null) {
          result.msgType_ = msgType_;
        } else {
          result.msgType_ = msgTypeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeaderProtocol.Header) {
          return mergeFrom((HeaderProtocol.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeaderProtocol.Header other) {
        if (other == HeaderProtocol.Header.getDefaultInstance()) return this;
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasCseq()) {
          setCseq(other.getCseq());
        }
        if (other.hasMsgType()) {
          mergeMsgType(other.getMsgType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasCseq()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeaderProtocol.Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeaderProtocol.Header) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 version = 1;
      private int version_ ;
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       * 协议版本号
       * </pre>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       * 协议版本号
       * </pre>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       * 协议版本号
       * </pre>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000001;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 version = 1;</code>
       *
       * <pre>
       * 协议版本号
       * </pre>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000001);
        version_ = 0;
        onChanged();
        return this;
      }

      // required int32 cseq = 2;
      private int cseq_ ;
      /**
       * <code>required int32 cseq = 2;</code>
       *
       * <pre>
       * 消息序列号
       * </pre>
       */
      public boolean hasCseq() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 cseq = 2;</code>
       *
       * <pre>
       * 消息序列号
       * </pre>
       */
      public int getCseq() {
        return cseq_;
      }
      /**
       * <code>required int32 cseq = 2;</code>
       *
       * <pre>
       * 消息序列号
       * </pre>
       */
      public Builder setCseq(int value) {
        bitField0_ |= 0x00000002;
        cseq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cseq = 2;</code>
       *
       * <pre>
       * 消息序列号
       * </pre>
       */
      public Builder clearCseq() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cseq_ = 0;
        onChanged();
        return this;
      }

      // optional .Header.MsgType msgType = 3;
      private HeaderProtocol.Header.MsgType msgType_ = HeaderProtocol.Header.MsgType.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          HeaderProtocol.Header.MsgType, HeaderProtocol.Header.MsgType.Builder, HeaderProtocol.Header.MsgTypeOrBuilder> msgTypeBuilder_;
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public HeaderProtocol.Header.MsgType getMsgType() {
        if (msgTypeBuilder_ == null) {
          return msgType_;
        } else {
          return msgTypeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder setMsgType(HeaderProtocol.Header.MsgType value) {
        if (msgTypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgType_ = value;
          onChanged();
        } else {
          msgTypeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder setMsgType(
          HeaderProtocol.Header.MsgType.Builder builderForValue) {
        if (msgTypeBuilder_ == null) {
          msgType_ = builderForValue.build();
          onChanged();
        } else {
          msgTypeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder mergeMsgType(HeaderProtocol.Header.MsgType value) {
        if (msgTypeBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              msgType_ != HeaderProtocol.Header.MsgType.getDefaultInstance()) {
            msgType_ =
              HeaderProtocol.Header.MsgType.newBuilder(msgType_).mergeFrom(value).buildPartial();
          } else {
            msgType_ = value;
          }
          onChanged();
        } else {
          msgTypeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public Builder clearMsgType() {
        if (msgTypeBuilder_ == null) {
          msgType_ = HeaderProtocol.Header.MsgType.getDefaultInstance();
          onChanged();
        } else {
          msgTypeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public HeaderProtocol.Header.MsgType.Builder getMsgTypeBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMsgTypeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      public HeaderProtocol.Header.MsgTypeOrBuilder getMsgTypeOrBuilder() {
        if (msgTypeBuilder_ != null) {
          return msgTypeBuilder_.getMessageOrBuilder();
        } else {
          return msgType_;
        }
      }
      /**
       * <code>optional .Header.MsgType msgType = 3;</code>
       *
       * <pre>
       * 消息类型
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          HeaderProtocol.Header.MsgType, HeaderProtocol.Header.MsgType.Builder, HeaderProtocol.Header.MsgTypeOrBuilder> 
          getMsgTypeFieldBuilder() {
        if (msgTypeBuilder_ == null) {
          msgTypeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              HeaderProtocol.Header.MsgType, HeaderProtocol.Header.MsgType.Builder, HeaderProtocol.Header.MsgTypeOrBuilder>(
                  msgType_,
                  getParentForChildren(),
                  isClean());
          msgType_ = null;
        }
        return msgTypeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Header)
    }

    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Header)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Header_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Header_MsgType_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Header_MsgType_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024HeaderProtocol.proto\"\317\001\n\006Header\022\017\n\007ver" +
      "sion\030\001 \002(\005\022\014\n\004cseq\030\002 \002(\005\022 \n\007msgType\030\003 \001(" +
      "\0132\017.Header.MsgType\032\203\001\n\007MsgType\0221\n\004type\030\001" +
      " \001(\0162\033.Header.MsgType.MessageType:\006NOTIF" +
      "Y\022\017\n\007extends\030\002 \001(\t\"4\n\013MessageType\022\013\n\007REQ" +
      "UEST\020\000\022\014\n\010RESPONSE\020\001\022\n\n\006NOTIFY\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Header_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Header_descriptor,
              new java.lang.String[] { "Version", "Cseq", "MsgType", });
          internal_static_Header_MsgType_descriptor =
            internal_static_Header_descriptor.getNestedTypes().get(0);
          internal_static_Header_MsgType_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Header_MsgType_descriptor,
              new java.lang.String[] { "Type", "Extends", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
