package first.netty_demo.netty;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EquipmentProtocol.proto

public final class EquipmentProtocol {
  private EquipmentProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EquipmentConfigOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .Header header = 1;
    /**
     * <code>required .Header header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>required .Header header = 1;</code>
     */
    HeaderProtocol.Header getHeader();
    /**
     * <code>required .Header header = 1;</code>
     */
    HeaderProtocol.HeaderOrBuilder getHeaderOrBuilder();

    // required string equipmentID = 2;
    /**
     * <code>required string equipmentID = 2;</code>
     */
    boolean hasEquipmentID();
    /**
     * <code>required string equipmentID = 2;</code>
     */
    java.lang.String getEquipmentID();
    /**
     * <code>required string equipmentID = 2;</code>
     */
    com.google.protobuf.ByteString
        getEquipmentIDBytes();

    // required string configInformation = 3;
    /**
     * <code>required string configInformation = 3;</code>
     */
    boolean hasConfigInformation();
    /**
     * <code>required string configInformation = 3;</code>
     */
    java.lang.String getConfigInformation();
    /**
     * <code>required string configInformation = 3;</code>
     */
    com.google.protobuf.ByteString
        getConfigInformationBytes();
  }
  /**
   * Protobuf type {@code EquipmentConfig}
   */
  public static final class EquipmentConfig extends
      com.google.protobuf.GeneratedMessage
      implements EquipmentConfigOrBuilder {
    // Use EquipmentConfig.newBuilder() to construct.
    private EquipmentConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EquipmentConfig(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EquipmentConfig defaultInstance;
    public static EquipmentConfig getDefaultInstance() {
      return defaultInstance;
    }

    public EquipmentConfig getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EquipmentConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              HeaderProtocol.Header.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(HeaderProtocol.Header.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              equipmentID_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              configInformation_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return EquipmentProtocol.internal_static_EquipmentConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return EquipmentProtocol.internal_static_EquipmentConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              EquipmentProtocol.EquipmentConfig.class, EquipmentProtocol.EquipmentConfig.Builder.class);
    }

    public static com.google.protobuf.Parser<EquipmentConfig> PARSER =
        new com.google.protobuf.AbstractParser<EquipmentConfig>() {
      public EquipmentConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EquipmentConfig(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EquipmentConfig> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .Header header = 1;
    public static final int HEADER_FIELD_NUMBER = 1;
    private HeaderProtocol.Header header_;
    /**
     * <code>required .Header header = 1;</code>
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .Header header = 1;</code>
     */
    public HeaderProtocol.Header getHeader() {
      return header_;
    }
    /**
     * <code>required .Header header = 1;</code>
     */
    public HeaderProtocol.HeaderOrBuilder getHeaderOrBuilder() {
      return header_;
    }

    // required string equipmentID = 2;
    public static final int EQUIPMENTID_FIELD_NUMBER = 2;
    private java.lang.Object equipmentID_;
    /**
     * <code>required string equipmentID = 2;</code>
     */
    public boolean hasEquipmentID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string equipmentID = 2;</code>
     */
    public java.lang.String getEquipmentID() {
      java.lang.Object ref = equipmentID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          equipmentID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string equipmentID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEquipmentIDBytes() {
      java.lang.Object ref = equipmentID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        equipmentID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string configInformation = 3;
    public static final int CONFIGINFORMATION_FIELD_NUMBER = 3;
    private java.lang.Object configInformation_;
    /**
     * <code>required string configInformation = 3;</code>
     */
    public boolean hasConfigInformation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string configInformation = 3;</code>
     */
    public java.lang.String getConfigInformation() {
      java.lang.Object ref = configInformation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          configInformation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string configInformation = 3;</code>
     */
    public com.google.protobuf.ByteString
        getConfigInformationBytes() {
      java.lang.Object ref = configInformation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        configInformation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      header_ = HeaderProtocol.Header.getDefaultInstance();
      equipmentID_ = "";
      configInformation_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHeader()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEquipmentID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConfigInformation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeader().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getEquipmentIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getConfigInformationBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, header_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getEquipmentIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getConfigInformationBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static EquipmentProtocol.EquipmentConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EquipmentProtocol.EquipmentConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EquipmentProtocol.EquipmentConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static EquipmentProtocol.EquipmentConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static EquipmentProtocol.EquipmentConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EquipmentProtocol.EquipmentConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static EquipmentProtocol.EquipmentConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static EquipmentProtocol.EquipmentConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static EquipmentProtocol.EquipmentConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static EquipmentProtocol.EquipmentConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(EquipmentProtocol.EquipmentConfig prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EquipmentConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements EquipmentProtocol.EquipmentConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return EquipmentProtocol.internal_static_EquipmentConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return EquipmentProtocol.internal_static_EquipmentConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                EquipmentProtocol.EquipmentConfig.class, EquipmentProtocol.EquipmentConfig.Builder.class);
      }

      // Construct using EquipmentProtocol.EquipmentConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeaderFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = HeaderProtocol.Header.getDefaultInstance();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        equipmentID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        configInformation_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return EquipmentProtocol.internal_static_EquipmentConfig_descriptor;
      }

      public EquipmentProtocol.EquipmentConfig getDefaultInstanceForType() {
        return EquipmentProtocol.EquipmentConfig.getDefaultInstance();
      }

      public EquipmentProtocol.EquipmentConfig build() {
        EquipmentProtocol.EquipmentConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public EquipmentProtocol.EquipmentConfig buildPartial() {
        EquipmentProtocol.EquipmentConfig result = new EquipmentProtocol.EquipmentConfig(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.equipmentID_ = equipmentID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.configInformation_ = configInformation_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof EquipmentProtocol.EquipmentConfig) {
          return mergeFrom((EquipmentProtocol.EquipmentConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(EquipmentProtocol.EquipmentConfig other) {
        if (other == EquipmentProtocol.EquipmentConfig.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (other.hasEquipmentID()) {
          bitField0_ |= 0x00000002;
          equipmentID_ = other.equipmentID_;
          onChanged();
        }
        if (other.hasConfigInformation()) {
          bitField0_ |= 0x00000004;
          configInformation_ = other.configInformation_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeader()) {
          
          return false;
        }
        if (!hasEquipmentID()) {
          
          return false;
        }
        if (!hasConfigInformation()) {
          
          return false;
        }
        if (!getHeader().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        EquipmentProtocol.EquipmentConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (EquipmentProtocol.EquipmentConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .Header header = 1;
      private HeaderProtocol.Header header_ = HeaderProtocol.Header.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          HeaderProtocol.Header, HeaderProtocol.Header.Builder, HeaderProtocol.HeaderOrBuilder> headerBuilder_;
      /**
       * <code>required .Header header = 1;</code>
       */
      public boolean hasHeader() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public HeaderProtocol.Header getHeader() {
        if (headerBuilder_ == null) {
          return header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder setHeader(HeaderProtocol.Header value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder setHeader(
          HeaderProtocol.Header.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder mergeHeader(HeaderProtocol.Header value) {
        if (headerBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              header_ != HeaderProtocol.Header.getDefaultInstance()) {
            header_ =
              HeaderProtocol.Header.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = HeaderProtocol.Header.getDefaultInstance();
          onChanged();
        } else {
          headerBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public HeaderProtocol.Header.Builder getHeaderBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      public HeaderProtocol.HeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_;
        }
      }
      /**
       * <code>required .Header header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          HeaderProtocol.Header, HeaderProtocol.Header.Builder, HeaderProtocol.HeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              HeaderProtocol.Header, HeaderProtocol.Header.Builder, HeaderProtocol.HeaderOrBuilder>(
                  header_,
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      // required string equipmentID = 2;
      private java.lang.Object equipmentID_ = "";
      /**
       * <code>required string equipmentID = 2;</code>
       */
      public boolean hasEquipmentID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string equipmentID = 2;</code>
       */
      public java.lang.String getEquipmentID() {
        java.lang.Object ref = equipmentID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          equipmentID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string equipmentID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEquipmentIDBytes() {
        java.lang.Object ref = equipmentID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          equipmentID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string equipmentID = 2;</code>
       */
      public Builder setEquipmentID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        equipmentID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string equipmentID = 2;</code>
       */
      public Builder clearEquipmentID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        equipmentID_ = getDefaultInstance().getEquipmentID();
        onChanged();
        return this;
      }
      /**
       * <code>required string equipmentID = 2;</code>
       */
      public Builder setEquipmentIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        equipmentID_ = value;
        onChanged();
        return this;
      }

      // required string configInformation = 3;
      private java.lang.Object configInformation_ = "";
      /**
       * <code>required string configInformation = 3;</code>
       */
      public boolean hasConfigInformation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string configInformation = 3;</code>
       */
      public java.lang.String getConfigInformation() {
        java.lang.Object ref = configInformation_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          configInformation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string configInformation = 3;</code>
       */
      public com.google.protobuf.ByteString
          getConfigInformationBytes() {
        java.lang.Object ref = configInformation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          configInformation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string configInformation = 3;</code>
       */
      public Builder setConfigInformation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        configInformation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string configInformation = 3;</code>
       */
      public Builder clearConfigInformation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        configInformation_ = getDefaultInstance().getConfigInformation();
        onChanged();
        return this;
      }
      /**
       * <code>required string configInformation = 3;</code>
       */
      public Builder setConfigInformationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        configInformation_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EquipmentConfig)
    }

    static {
      defaultInstance = new EquipmentConfig(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EquipmentConfig)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EquipmentConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EquipmentConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027EquipmentProtocol.proto\032\024HeaderProtoco" +
      "l.proto\"Z\n\017EquipmentConfig\022\027\n\006header\030\001 \002" +
      "(\0132\007.Header\022\023\n\013equipmentID\030\002 \002(\t\022\031\n\021conf" +
      "igInformation\030\003 \002(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_EquipmentConfig_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_EquipmentConfig_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EquipmentConfig_descriptor,
              new java.lang.String[] { "Header", "EquipmentID", "ConfigInformation", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          HeaderProtocol.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
